Develop 1
11Nastiv/Program_save pull request #1
Opened 2023-05-14 14:12 UTC by 11Nastiv

Программа, передающая фотографии из папки Downloads в нужную папку.

2023-05-18 10:10 UTC, sergei-prokhorov-igorevich commented
> Программа, передающая фотографии из папки Downloads в нужную папку.

Не бывает папок, правильное название - 'каталог'. :)

2023-05-18 10:23 UTC, sergei-prokhorov-igorevich requested changes

2023-05-18 10:23 UTC, sergei-prokhorov-igorevich commented on program.py
> +try:
На 23 строке описать комментарием что делает цикл. Например, запускается цикл и каждые 10мс проверяет каталог на наличие файлов.

2023-05-19 11:16 UTC, 11Nastiv commented on program.py
> +try:
Сделала.

2023-05-20 05:00 UTC, sergei-prokhorov-igorevich commented
Замечаний нет, ПР можно вливать.

2023-05-21 01:31 UTC, merged